### ISSUE TITLE
EcomDev Indexers are not working in Magento 1.13

### ISSUE THREAD

**Issue by sgrund** [EcomDev/EcomDev_PHPUnit#149]
In the file \EcomDev_PHPUnit_Model_Mysql4_Fixture_Eav_Abstract
The method runRequiredIndexers is running all indexes, but the indexers are executed on dummy objects, due to the new enterprise indexers.

How can we resolve this issue, so that the index is correctly built for products or categories created by fixtures?

**Comment by IvanChepurnyi** [comment]
The issue is gets worked on in EcomDev_Fixture module, that is going to generate index data during importing a fixutre.
