### ISSUE TITLE
Issues in create test case for magento controller function

### ISSUE THREAD

**Issue by gadhavims** [EcomDev/EcomDev_PHPUnit#16]
1) PHP Fatal error:  Call to undefined method Mage_Core_Controller_Request_Http:
:reset() in C:\xampp\htdocs\Cacommons\app\code\community\EcomDev\PHPUnit\Test\Ca
se\Controller.php on line 1905

Fatal error: Call to undefined method Mage_Core_Controller_Request_Http::reset()
 in C:\xampp\htdocs\Cacommons\app\code\community\EcomDev\PHPUnit\Test\Case\Contr
oller.php on line 1905

2) PHP Fatal error:  Call to undefined method CA_Comparesort_Test_Controller_Index
::getMockBuilder() in C:\xampp\htdocs\Cacommons\app\code\community\EcomDev\PHPUn
it\Test\Case.php on line 406

Fatal error: Call to undefined method CA_Comparesort_Test_Controller_Index::getM
ockBuilder() in C:\xampp\htdocs\Cacommons\app\code\community\EcomDev\PHPUnit\Tes
t\Case.php on line 406

**Comment by aait** [comment]
Hello, i have same problem.
I have:
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.23
Configuration: phpunit.xml

PHP Fatal error:  Call to undefined method Mage_Core_Controller_Request_Http::reset() in app/code/community/EcomDev/PHPUnit/Test/Case/Controller.php on line 1990

Fatal error: Call to undefined method Mage_Core_Controller_Request_Http::reset() in app/code/community/EcomDev/PHPUnit/Test/Case/Controller.php on line 1990

Test:
```
class PayEx_Payments_Test_Block_Info_Autopay extends EcomDev_PHPUnit_Test_Case_Controller
{
    var $object;

    /**
     * setUp
     */
    public function setUp()
    {
        parent::setUp();
    }

    /**
     * tearDown
     */
    public function tearDown()
    {
        parent::tearDown();
    }
}
```

Environment:
Magento CE 1.7.0.2
PHP 5.6
MariaDB 10
EcomDev_PHPUnit from dev branch
