### ISSUE TITLE
Autoload not working

### ISSUE THREAD

**Issue by jameswithers** [EcomDev/EcomDev_PHPUnit#218]
`Fatal error: Uncaught exception 'InvalidArgumentException' with message '$object should be a valid class name or object instance'`, which is traced back to https://github.com/EcomDev/EcomDev_PHPUnit/blob/master/app/code/community/EcomDev/PHPUnit/Test/Suite.php#L45. It fails because the Composer ClassLoader cannot find `EcomDev_Utils_Reflection`.

**Comment by IvanChepurnyi** [comment]
How did you install an extension?

**Comment by jameswithers** [comment]
@IvanChepurnyi no longer have access to this install, but I've not seen the error since ran script after shell installation (https://github.com/EcomDev/EcomDev_PHPUnit/issues/219)
