### ISSUE TITLE
Composer installation documentation

### ISSUE THREAD

**Issue by jameswithers** [EcomDev/EcomDev_PHPUnit#219]
Re: https://github.com/EcomDev/EcomDev_PHPUnit/issues/217#issuecomment-55907746, the README should state that if using Composer to install, the additional step of calling the install shell script must be performed manually.

**Comment by IvanChepurnyi** [comment]
project and module parameters are deprecated, since they can be obtained by retrieving data from environment.

**Comment by jameswithers** [comment]
@IvanChepurnyi please re-open/resolve: see #217 (comment), the README should state that if using Composer to install, the additional step of calling the install shell script must be performed manually.
