### ISSUE TITLE
Install Issue on Admin Session

### ISSUE THREAD

**Issue by dtirer** [EcomDev/EcomDev_PHPUnit#238]
After installing this package and running the initial `phpunit` command, I get failures for every method in the `EcomDev_PHPUnitTest_Test_Helper_Session` class, and one error.

There error is:

`1) EcomDev_PHPUnitTest_Test_Helper_Session::testAdminSessionAllRights
Exception: Warning: simplexml_load_string(): Entity: line 10: parser error : Start tag expected, '<' not found  in /var/www/lib/Varien/Simplexml/Config.php on line 510`

If I comment out the 3 tests in this class (`testAdminSessionAllRights, testAdminSessionOnlyCatalog, testAdminSessionOnlyCatalogProduct`) then everything passes correctly.

Any advice?

**Comment by IvanChepurnyi** [comment]
Seems like you have an extension that has a broken xml file structure. Run this command to find out which file is broken:

```bash
find . -type f -name '*.xml' ! -name 'wsi.xml' ! -name 'wsdl*.xml' | xargs -I '{}' php -r 'simplexml_load_file("{}");'
```

**Comment by dtirer** [comment]
Hi @IvanChepurnyi I tried running that command, and it just returned the usage gudie for the `php` command, many times (recursively).  Is there perhaps an error in that statement?
