### ISSUE TITLE
Test Isolation

### ISSUE THREAD

**Issue by danelowe** [EcomDev/EcomDev_PHPUnit#240]
I believe it would be a good idea to look at what could be done to keep tests isolated from one another so that their behaviour does not change depending on the order of test runs. Some things to look at could be:

1. Can each test be run in a single database transaction that is rolled back at the end of each?
2. Can we look at a way of clearing Magento's singleton registry between tests, or provide a method to do so manually?
3. What can be done to isolate configuration options?

I am happy to put some time into this when I can. However, there is not much point if it does not align with the project goals/opinions.

**Comment by IvanChepurnyi** [comment]
You should take a look at fixtures and `@registry key`, `@singleton class/alias`. Those ones already rollback data that you load for your test.

**Comment by danelowe** [comment]
Apologies, I don't understand your response.

Where should I be looking in order to find out how to clear memoised data from a singleton?

Also, my understanding is that the fixtures only 'rollback' the data by clearing the tables that are affected by a fixture as it is loaded, and does not ensure the data is back to a pristine state ready for the next test. 

Are you welcoming contribution to this project? If so, some guidance would be appreciated. Perhaps I can look at updating documentation. If not, then please let me know.

**Comment by IvanChepurnyi** [comment]
Hi Denelowe,

I accept contribution, but at the moment fixutres gets haviely rafactored, into a separate module, that will have this kind of backup functionality. 

As for singletons, very easy, just specify `@singleton eav/config` in your doc block for test method, and singleton with name eav/config will get replaced before test with null and after test will be restored to previous value.

**Comment by IvanChepurnyi** [comment]
I would greately appreciate contributions to wiki or creating docs/ directory with markdown files describing extension documentation. 

You can find very outdated documentation in http://www.ecomdev.org/wp-content/uploads/2011/05/EcomDev_PHPUnit-0.2.0-Manual.pdf.

The manual is not exported yet.
