### ISSUE TITLE
Calling Helper from a Model unit test, gives back wrong class

### ISSUE THREAD

**Issue by Ilia** [EcomDev/EcomDev_PHPUnit#266]
I have a unit test for a modal that internally calls a helper from the same plugin.

So my test looks like this:

```
class Myplugin_Social_Test_Model_Facebook extends EcomDev_PHPUnit_Test_Case {
    /**
     * Dummy test
     *
     * @test
     */
    public function testDummy() {
       echo get_class( Mage::helper('social') ) ;
    }
}
```

The echo should produce: 
```
Myplugin_Social_Helper_Data
```
Instead I get:
```
Fatal error: Class 'Mage_Social_Helper_Data' not found in /path/to/magento/app/Mage.php on line 547
```

This is of 1.14.1 EE of Magento.

Please let me know if I missed a configuration or setting somewhere.

**Comment by robbieaverill** [comment]
@Ilia looks to me like your module is missing the helper configuration. Does this work if you run it from a shell script instead of through PHPUnit?

**Comment by Ilia** [comment]
Yeah, i figure out what it was late yesterday, we have a special setup that based on store it will load certain modules, we are passing options to Mage:app() to do that, so the etc folder is different, now ecomdev overwrites the config and does not preserve the options. So i had to patch the Ecom dev model app to keep the options for config. 

Now i just need to figure out how to build a database based on the store context :( 

Thanks for the help.
