### ISSUE TITLE
Controller PHPUnit

### ISSUE THREAD

**Issue by Ig0r-M** [EcomDev/EcomDev_PHPUnit#278]
### Spec 
Upon work done in **It workshop - PHPUnit Testing** this issue was raised to complete phpunit for ProductController ukRedirect action which is has been started in branch `issue/phpUnit/unfinishedCases` and update PHPUnit.md with information how to create a new PHPUnit Controller testCase that will serve as future reference.

### Examples
**Nathan please populate here examples for reference**

### UAT
- [ ] TestProductController is done and working correctly
- [ ] PHPUnit.md is updated with related information

**Comment by NathanDayMF** [comment]
please close this issue as was raised incorrectly on the wrong repo

**Comment by Ig0r-M** [comment]
Sorry guys wrong repo
